### PR TITLE
alpha版リリース準備

### PR DESCRIPTION
**Pull request by satoshicano**
- [x] アプリのビルド
- [x] 画像path解決

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-app/25)

### CODE REVIEW

**Comment by hrl7** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main.js, line 3 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25#-KotVS25nx2RREhoFBsm:-KotVS25nx2RREhoFBsn:bvcj55e) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/0f7190c438d9e015069c420e0636e53796da8537/src/main.js#L3)):*
> ```JavaScript
> 'use strict';
> const{ app, BrowserWindow, globalShortcut } = require('electron');
> // const loadDevtool = require('electron-load-devtool');
> ```

process.env.NODE_ENVとかをみて適宜requireするようにしたい

---

*[src/main.js, line 23 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25#-KotVcISOmU8SWtWXvEq:-KotVcISOmU8SWtWXvEr:ba0t9en) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/0f7190c438d9e015069c420e0636e53796da8537/src/main.js#L23)):*
> ```JavaScript
> 
>   // loadDevtool(loadDevtool.REACT_DEVELOPER_TOOLS);
>   // loadDevtool(loadDevtool.REDUX_DEVTOOLS);
> ```

devとproductionでわけたい

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25)*

**Comment by satoshicano** [comment]
Review status: 2 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main.js, line 3 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25#-KotVS25nx2RREhoFBsm:-KovN_Ufws8KQtHin0eQ:b-896fix) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/0f7190c438d9e015069c420e0636e53796da8537/src/main.js#L3)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

process.env.NODE_ENVとかをみて適宜requireするようにしたい
</blockquote></details>

Done.

---

*[src/main.js, line 23 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25#-KotVcISOmU8SWtWXvEq:-KovNbYTR25LWX60rhjI:b-896fix) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/0f7190c438d9e015069c420e0636e53796da8537/src/main.js#L23)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

devとproductionでわけたい
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25)*

**Comment by hrl7** [comment]
Reviewed 1 of 7 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.js, line 21 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25#-KovQhOIOrMPPOfVLLCz:-KovQhOJtYRqttG5M9SK:bqqb9mu) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/d94c9a6ecdcfaabeedcf30e54a2183ea0d41d28d/src/main.js#L21)):*
> ```JavaScript
>     mainWindow.loadURL('file://' + __dirname + '/index.html');
> 
>     if(process.env.NODE_ENV === 'production') {
> ```

productionのときに開発用ツールを仕込むの？ここの条件逆だと思う。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25)*

**Comment by hrl7** [comment]
Reviewed 1 of 7 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25)*

**Comment by fmsuvM** [comment]
Reviewed 4 of 7 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/25)*

**Comment by satoshicano** [comment]
確認してもらったのでマージします

**Pull request merged**
