### PR TITLE
refactor state.manager

### PR DESCRIPTION
**Pull request by fmsuvM**
stateの再設計中
- [ ] : `ProjectElement` に内蔵されているMenuをComponentとして独立させる
- [x] : mouseHoverはstoreが知るべき情報ではないので消す
- [x] : redux-actionの `createAction` を使う

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-app/20)

### CODE REVIEW

**Comment by hrl7** [comment]
ActionTypeを文字列で直接埋め込んでしまうと, タイポとかに気付きにくくなる気がする。まぁ, 実際どうするかという, その辺の判断は任せるけど。

---

Reviewed 9 of 10 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/actions/manager.js, line 6 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXuRQ1nVnGPjSyV59s:-KoXuRQ35MMU4_XPgNNf:buhlz53) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/actions/manager.js#L6)):*
> 不要なActionCreatorはわざわざつくらなくて良いと思う

---

*[src/actions/manager.js, line 11 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXuvBPWc9Khh2nfmVg:-KoXuvBQNKqZbYCvZ_uC:bh0t2pq) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/actions/manager.js#L11)):*
> ```JavaScript
> export const exitDetail = createAction('EXIT_DETAIL');
> export const willUpdateProjectList = createAction('WILL_UPDATE_PROJECT_LIST');
> export const backHome = createAction('BACK_HOME');
> ```

backHomeもreact-router-reduxのactionつかえば良いと思う

---

*[src/components/ProjectDetail.jsx, line 68 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXvXaqBRlQVED46_eD:-KoXvXar_o1_G0Gm15Ba:bj5in7y) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectDetail.jsx#L68)):*
> ```JSX
> };
> function mapStateToProps(state) {
>     return state;
> ```

なるべくmapStateToPropsで, 最低限のものだけを渡したい。
targetProjectしか使わないのであれば, managerすべてを渡すのではなく, targetProjectのみを渡すようにしたい

---

*[src/components/ProjectElement.jsx, line 132 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXvzgCo8UtxJBuO32p:-KoXvzgDzA4l6DNnkdof:b-1ppjpl) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectElement.jsx#L132)):*
> ```JSX
>             debug('click menu');
>             dispatch({
>                 type: 'SELECT_PROJECT_MENU',
> ```

redux-actionsのcreateActionでactionCreatorを作ってしまいたい。
mapDispatchToPropsでactionCreatorを作ってしまうと, 再利用しづらくなるし, いろいろ面倒くさそう

あれだったらducks file structureとか参考にするとよい

---

*[src/components/ProjectList.jsx, line 59 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXwIYu2MsyS2ZUUsM9:-KoXwIYu2MsyS2ZUUsMA:b-t647z9) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectList.jsx#L59)):*
> ```JSX
>         path: PropTypes.string
>     }),
>     over: PropTypes.func,
> ```

overは不要だと思う

---

*[src/components/ProjectMenu.jsx, line 21 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXwV9zK0UzRDW-XUkD:-KoXwV9zK0UzRDW-XUkE:b-lzf42r) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectMenu.jsx#L21)):*
> ```JSX
>         const actions = this.props.menuType == 'allProjects' ? (
>             <ul className="actions">
>                 <li
> ```

li要素以下は共通部分がおおく, 別のコンポーネントにしてしまった方がすっきりしそう

---

*[src/components/ProjectMenu.jsx, line 57 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXwqcMXXEy5axhgi6i:-KoXwqcN7AYmu-E-VBh3:b4egrba) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectMenu.jsx#L57)):*
> ```JSX
>                     this.selectMenuAction('detail')
>                 }}>
>                 <div className=".menu5">
> ```

CSSセレクタで, `..menu5` と `.menu5` を使い分けるつもりなのか, ただのタイポなのか

---

*[src/components/ProjectMenu.jsx, line 66 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXwexqQMMH79DSxiWA:-KoXwexqQMMH79DSxiWB:bl9uscv) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectMenu.jsx#L66)):*
> ```JSX
>                     this.selectMenuAction('edit')
>                 }}>
>                 <div className="menu5">
> ```

menu5とかmenu4というclassNameはよろしくない。
しかも, menu5のしたにmenu4がくるのはもう何が何だかわからない。。。

---

*[src/components/ProjectMenu.jsx, line 108 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXx4NYXcR347D8PrWR:-KoXx4NYXcR347D8PrWS:b-jpwcqn) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectMenu.jsx#L108)):*
> ```JSX
>                 type: 'SELECT_PROJECT_MENU',
>                 targetProject: project,
>                 mode: mode
> ```

このへんのactionCreatorもここに埋めないほうがよい

---

*[src/reducers/manager.js, line 47 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXxJz_x9D4wlDpGj4m:-KoXxJz_x9D4wlDpGj4n:blw7erc) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/reducers/manager.js#L47)):*
> ```JavaScript
>         });
>     },
>     BACK_HOME: (state, action) => {
> ```

現在のモードってreact-routerのactionを捕まえるとわかる気がするけど。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-:-KoXv9hNtKCw4OYB8sJM:b-hhufp3)*

**Comment by fmsuvM** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/components/ProjectElement.jsx, line 132 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXvzgCo8UtxJBuO32p:-KoXyaK8dyYL9t5Yyw7p:brkr0xq) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectElement.jsx#L132)):*
> redux-actionsのcreateActionでactionCreatorを作る
というのは， `/actions` 内のファイルで

```
export function selectMenuAction(projectId, mode) {
    return { 
        type: selectProjectMenu,
        targetProject: projectId,
        mode: mode 
   }
}
```

というのを作って，それぞれのcomponentでこの関数を呼び出すという解釈でいいのでしょうか？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20)*

**Comment by fmsuvM** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/components/ProjectMenu.jsx, line 66 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXwexqQMMH79DSxiWA:-KoY-4nrVkfwHSNmKZcs:b-ufi3di) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectMenu.jsx#L66)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

menu5とかmenu4というclassNameはよろしくない。
しかも, menu5のしたにmenu4がくるのはもう何が何だかわからない。。。
</blockquote></details>

classNameは前から引き継ぎのままです．
修正するのは必須だと思います

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20)*

**Comment by fmsuvM** [comment]
```
export FETCHING_PROJECTS = ('FETCHING_PROJECTS');
export const fetchingProjects = createAction(FETCHING_PROJECTS);
```
にするということでしょうか？

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-:-KoY-ZWpyaF0swAZfK7O:b-vxnmqo)*

**Comment by hrl7** [comment]
だいたいそんなかんじ。文字列をベタに打ち込んでもいいけど, それでできたバグを取るのは結構面倒だと思う。タイポしてもエラー吐かないから。
```
export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const fetchingProjects = createAction(FETCHING_PROJECTS);
```

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/components/ProjectElement.jsx, line 132 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXvzgCo8UtxJBuO32p:-KoY0_Fk-OyJ2yqC1MFF:brzpdbe) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectElement.jsx#L132)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

> redux-actionsのcreateActionでactionCreatorを作る
というのは， `/actions` 内のファイルで

```
export function selectMenuAction(projectId, mode) {
    return { 
        type: selectProjectMenu,
        targetProject: projectId,
        mode: mode 
   }
}
```

というのを作って，それぞれのcomponentでこの関数を呼び出すという解釈でいいのでしょうか？
</blockquote></details>

そういうこと。もしくは
```
export const selectMenuAction = createAction(SELECT_PROJECT_MENU, (projectId, mode) => {
  return { targetProject: projectId, mode };
});
```

---

*[src/components/ProjectMenu.jsx, line 66 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-KoXwexqQMMH79DSxiWA:-KoY0tLp8TxvPi1LJ-cK:b-erasjf) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/803a1d5d19514ecbb51bda0f9a9071cc8b3597b2/src/components/ProjectMenu.jsx#L66)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

classNameは前から引き継ぎのままです．
修正するのは必須だと思います
</blockquote></details>

なるほどね。さすがにそうか。issueに立てといてくれるとたすかる

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-:-KoY0CgcVpSwvOmscfiZ:b-6q6yl8)*

**Comment by hrl7** [comment]
Reviewed 7 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/reducers/manager.js, line 45 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-Ko_dIIQgiJfu3f7ui9d:-Ko_dIIQgiJfu3f7ui9e:be529vm) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/01d61257b632205be391d22c0af38e886b381afc/src/reducers/manager.js#L45)):*
> ```JavaScript
>             projects: action.projects,
>             canUpdatePage: false,
>             isFetching: false
> ```

これ、initialStateにないけど大丈夫？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20)*

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20)*

**Comment by hrl7** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/20#-:-KoaF9cJwDJX2X3iDiHU:bnfp4nl)*

**Comment by hrl7** [comment]
git rebaseでコミットログを綺麗にする前に, このPRで何をしたのかをよく考えて洗い出してからコミットログを綺麗にしよう。

たぶんざっと見てこんな感じになるはず。

- `state.manager` の中を再設計
- それにともなって不要なActionTypeの削除やコンポーネントでのpropsの扱いを修正
- actionCreatorをredux-actionsのcreateActionで置き換え
- ProjectElementのメニューを別コンポーネントへ切り出し

それを踏まえて, コードをどういう状態からどういう状態へ変更したのかを意味のある単位でコミットしなおすことによって, ログを綺麗に保ちたいわけだ。

--- 
以下, 俺ならこうする的なメモ。

最初の2コミット 56b2bbd 37133a2 は明らかに不要。mouse hover関係と `BACK_HOME` なので。あとこれにともなって e437785f0 も消える

次のコミット 457a0cf はコミットメッセージからはわかりづらいが, menuをクリックしたときのハンドラを登録しているから必要, メッセージは直そう

f22b879 から 9129798 は stateの再設計が行われている。ここは1コミットにまとめて良いと思う。isFetchingを消しているけれども, ここの時点で残しておけば,  561f0f4 が消せる

0a17c696 は 9fef3ecf と統合してしまうのがよさそう
それからメッセージを直そう。action eventsというのがなんのことか曖昧だし, using libraryというのもなんのライブラリなのかわからなくて良くない。書くなら, `refactor action creators with redux-actions` とかで良いと思う

7914b761 は1行目ではProject Cardと呼んでいるが3行目以降ではProject Elementになっててよくない。ElementというよりはCardというのはその通りだなと思うので, そのうちリネームしたい。
`Add: Menu on Project Card component` だと, Menuを追加した感じがする。しかし分割しただけなので, `refactor: divide Menu Component from ProjectElement` とかの方が良いと思う

090d605 actionを追加していない。reducerを変更して, actionをハンドルするようにした。

0bf22d `Add: @@router/LOCATION_CHANGE action` だと, 新たなactionを追加したように見える。しかし実際は, reducerにすでにあるactionをハンドルするように書き換えただけなので, `Add: @@router/LOCATION_CHANGE action handler to manager reducer for changing mode` とかの方がよいとおもう

b25411c5 todoを追加するくらいならissueたてよう。そしてメッセージの1行目より5行目がとても重要になっていてよくない。だいじなことは1行目に書こう。
`state全部ではなく，最低限必要なものにした` とかより `componentに渡すstateを最小限にした` とした方がわかりやすい

e437785 Remove: unnecessary state とあるが, stateは削除してない。バリデーションを削除しただけ。

**Pull request merged**
