### PR TITLE
Help-page実装完了

### PR DESCRIPTION
**Pull request by tkatsuya**
大まかな体裁の完了。
見るぶんにはとりあえず大丈夫という感じにした。

今後help-pageのレイアウトを付け加えて行く際はその都度変更する。

次の作業としてバックボタンと更新ボタンのレイアウトを行なって行く。

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-app/14)

### CODE REVIEW

**Comment by fmsuvM** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/components/HelpPage.jsx, line 2 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7m3HvXiyXuZvozkjn:-Ko7m3HvXiyXuZvozkjo:b-vh8qpn) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L2)):*
> ```JSX
> import React from 'react';
> import ReactDOM from 'react-dom';
> ```

使わないpackageは消しちゃおう

---

*[src/components/HelpPage.jsx, line 8 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mDleUMZ9MtyVNCYV:-Ko7mDleUMZ9MtyVNCYW:b1ep1z2) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L8)):*
> export default function HelpPage() {
>     return (

```
export default class HelpPage extends React.Component {
    render() {
        return (
            <div>....
```  

とかで良い気がする

---

*[src/components/HelpPage.jsx, line 9 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mVS2qVM0vJCRxl-_:-Ko7mVS2qVM0vJCRxl-a:b-k0ec4n) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L9)):*
> ```JSX
> export default function HelpPage() { 
>     return (
>         <div className="helppage">
> ```

インデントがおかしいので，pushする前に最後に `npm run lint:fix` しよう

---

*[src/stylesheets/application/application.scss, line 130 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mmidChGvFV1NZwIB:-Ko7mmidChGvFV1NZwIC:b-qpd72g) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/stylesheets/application/application.scss#L130)):*
> ```SCSS
>   }
> }
> .search-bar {
> ```

検索窓でhelp pageに飛ぶボタンが押せないのはちょっとイマイチなので，検索窓をもう少し端に寄せよう

---

*[src/stylesheets/application/application.scss, line 210 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mzDZuBOd-ZaOk7QO:-Ko7mzD_59XCTGiaE19-:b-m1yhky) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/stylesheets/application/application.scss#L210)):*
> ```SCSS
>   padding-left: 400px;
> }
> .helppage{
> ```

要素が重なって押せないっぽいので，ちゃんと押せるようにしてほしいかも
欲を言えばアイコンがいい

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by fmsuvM** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by hrl7** [comment]
Reviewed 14 of 15 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/components/HelpPage.jsx, line 8 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mDleUMZ9MtyVNCYV:-Ko7zsR5kLRETR9-aUlZ:b-ejoza3) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L8)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

> export default function HelpPage() {
>     return (

```
export default class HelpPage extends React.Component {
    render() {
        return (
            <div>....
```  

とかで良い気がする
</blockquote></details>

あ, functionは使わずにarrow-functionがよい

---

*[src/stylesheets/application/application.scss, line 210 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko8-CGTdWKEI2MmagsS:-Ko8-CGTdWKEI2MmagsT:b2gl8as) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/97e282ddf3500b8994dbe6b62d74c63d5a1683c6/src/stylesheets/application/application.scss#L210)):*
> ```SCSS
>   padding-left: 400px;
> }
> .helppage{
> ```

クラス名は, `kebab-case` がよい。ハイフンで単語同士を繋げた方がよみやすいよ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
分かりました。
ハイフンでつなげるようにします。

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/components/HelpPage.jsx, line 9 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mVS2qVM0vJCRxl-_:-Ko9jMP5C4i0Zp3SW6vC:bo2hylo) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L9)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

インデントがおかしいので，pushする前に最後に `npm run lint:fix` しよう
</blockquote></details>

@fmsuvm このコメントはreplyに書いた方がよいかも

---

*[src/stylesheets/application/application.scss, line 265 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko9jbM5QFOaJKZF5tjJ:-Ko9jbM6jU0ncv52TFZf:bs30zww) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/961f3cdf1859d906070508d7eaa35f728a6199dd/src/stylesheets/application/application.scss#L265)):*
> ```SCSS
>   color: #ff00ff;
> }
> .noUpdate {
> ```

これもno-updateがよい。また, update/no-updateは汎用的な言葉なので, どこかで被る可能性が高いから, 変えた方がよいかもしれない

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
そこは、僕が記述したわけではありませんでしたが、修正しておきます、、、

**Comment by hrl7** [comment]
たすかるー。あれだったらissue立てとくだけでもよい

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/stylesheets/application/application.scss, line 265 at r4](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-KoBFwRvHNWhaY87ODa9:-KoBFwRwLcJYzu-JkNoo:bw74ak8) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/41374966ab5bdbc11259c4c889cc7e179baf1cbf/src/stylesheets/application/application.scss#L265)):*
> ```SCSS
>   color: #ff00ff;
> }
> .state-no-update{
> ```

なんだかもう少しいい名前がある気もする。。。もやもやする。まぁこのままでもいいけど。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
cssファイルのコードリファクタリング時に直していきます。

**Comment by tkatsuya** [comment]
*[src/stylesheets/application/application.scss, line 210 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mzDZuBOd-ZaOk7QO:-KoBLRyfyjik-m15e9KR:bvy95u7) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/stylesheets/application/application.scss#L210)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

要素が重なって押せないっぽいので，ちゃんと押せるようにしてほしいかも
欲を言えばアイコンがいい
</blockquote></details>

アイコンにしました。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/stylesheets/application/application.scss, line 265 at r4](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-KoBFwRvHNWhaY87ODa9:-KoBKOq3jgvyDRH8mowg:b-m40aja) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/41374966ab5bdbc11259c4c889cc7e179baf1cbf/src/stylesheets/application/application.scss#L265)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

なんだかもう少しいい名前がある気もする。。。もやもやする。まぁこのままでもいいけど。
</blockquote></details>

クラス名に関してはscssリファクタリング時に直したいと思っています。
他のファイルにも元からある部分と統一されていない部分があると思うので、、

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/components/HelpPage.jsx, line 9 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mVS2qVM0vJCRxl-_:-KoBOdrwdDKTKJIHD6jh:b1rcm3i) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L9)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

@fmsuvm このコメントはreplyに書いた方がよいかも
</blockquote></details>

今後やっていきます。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/stylesheets/application/application.scss, line 130 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mmidChGvFV1NZwIB:-KoBLf2wu9_wI2IvrRM0:b-jgnda7) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/stylesheets/application/application.scss#L130)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

検索窓でhelp pageに飛ぶボタンが押せないのはちょっとイマイチなので，検索窓をもう少し端に寄せよう
</blockquote></details>

修正しました

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/stylesheets/application/application.scss, line 265 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko9jbM5QFOaJKZF5tjJ:-KoBOlUVSkyS-33mVHhT:b-nnul8g) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/961f3cdf1859d906070508d7eaa35f728a6199dd/src/stylesheets/application/application.scss#L265)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

これもno-updateがよい。また, update/no-updateは汎用的な言葉なので, どこかで被る可能性が高いから, 変えた方がよいかもしれない
</blockquote></details>

update, no-updateはボタンの状態らしいのでstateをつけました。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by hrl7** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/components/HelpPage.jsx, line 9 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mVS2qVM0vJCRxl-_:-KoBOm53qKlIXhONSj5x:b-5vt5xl) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L9)):*
<details><summary><i>Previously, tkatsuya wrote…</i></summary><blockquote>

今後やっていきます。
</blockquote></details>

push前に `npm run lint:fix` だけはやってくれ。

---

*[src/stylesheets/application/application.scss, line 265 at r4](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-KoBFwRvHNWhaY87ODa9:-KoBP29je-K60pKVvP_w:b2ur0c6) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/41374966ab5bdbc11259c4c889cc7e179baf1cbf/src/stylesheets/application/application.scss#L265)):*
<details><summary><i>Previously, tkatsuya wrote…</i></summary><blockquote>

クラス名に関してはscssリファクタリング時に直したいと思っています。
他のファイルにも元からある部分と統一されていない部分があると思うので、、
</blockquote></details>

おけ。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/stylesheets/application/application.scss, line 210 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko8-CGTdWKEI2MmagsS:-KoBP69JtfjR0UlWUa19:br6t3gm) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/97e282ddf3500b8994dbe6b62d74c63d5a1683c6/src/stylesheets/application/application.scss#L210)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

クラス名は, `kebab-case` がよい。ハイフンで単語同士を繋げた方がよみやすいよ
</blockquote></details>

今後そうしていきます。help-page内でのクラス名はハイフンに直しました。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/components/HelpPage.jsx, line 2 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7m3HvXiyXuZvozkjn:-KoBKt-SANWcDH-3ykI2:b-u2eq34) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L2)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

使わないpackageは消しちゃおう
</blockquote></details>

消しました。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Comment by tkatsuya** [comment]
*[src/components/HelpPage.jsx, line 9 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14#-Ko7mVS2qVM0vJCRxl-_:-KoBPVXZdX3C41KkBSd0:b-49fjv0) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/de7ef04fedce2cbda8d894305f79dc3493dd2d38/src/components/HelpPage.jsx#L9)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

push前に `npm run lint:fix` だけはやってくれ。
</blockquote></details>

はい。わかりました。気をつけます。
走らせたつもりでpushしていますが、それでもおかしな点があれば連絡お願いいたします。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/14)*

**Pull request merged**
