### PR TITLE
add help-page

### PR DESCRIPTION
**Pull request by tkatsuya**
組み立て方の説明文と説明イメージ図の追加

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-app/32)

### CODE REVIEW

**Comment by fmsuvM** [comment]
Reviewed 1 of 32 files at r1.
Review status: 1 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/HelpPage.jsx, line 96 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/32#-KpIsmVs8UqzsbrSCE9q:-KpIsmVs8UqzsbrSCE9r:bddxutb) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/4b776cc98c9fa679ed615abb7affa3496043a359/src/components/HelpPage.jsx#L96)):*
> ```JSX
>                         </div>
>                         
>                     </div>]<div className="parts">
> ```

変な文字が混ざっている

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/32)*

**Comment by fmsuvM** [comment]
以前から少し思っていたのだけど，灰色の背景に黒文字って，周囲の色が白なのでかなり暗く見えてしまう．
黒い枠線をつけるのはありかもしれないけど，中身を灰色でfillする必要はないと思う

あと，一つの要素は
文章 | 画像
ではなくて
画像 | 文章
という構成のほうがいいかもしれない

**Comment by fmsuvM** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 33 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/32#-:-KpIvG4P5K7wYHGYJE43:bnfp4nl)*

**Comment by tkatsuya** [comment]
Review status: 1 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/HelpPage.jsx, line 96 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/32#-KpIsmVs8UqzsbrSCE9q:-KpIyQT6GqVWSWu9fWq0:b-896fix) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/4b776cc98c9fa679ed615abb7affa3496043a359/src/components/HelpPage.jsx#L96)):*
<details><summary><i>Previously, fmsuvM (Kazuma Takada) wrote…</i></summary><blockquote>

変な文字が混ざっている
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/32)*

**Comment by hrl7** [comment]
:lgtm:

---

Reviewed 31 of 32 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/32#-:-KpIzhYe1Dcl_tKuA1FN:bnfp4nl)*

**Pull request merged**
