### PR TITLE
Update react router to v4

### PR DESCRIPTION
**Pull request by hrl7**
* Component: props.params => props.match.params
* Store: state.routing => state.router
* package: react-router => react-router-dom
* remove 'syncHistoryWithStore'

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-app/6)

### CODE REVIEW

**Comment by fmsuvM** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 73 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/6#-KnXKIqXjK8Q_W3xeOW9:-KnXKIqXjK8Q_W3xeOWA:ba8fvo9) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/9ab2d5df0349356f1bedbf27281ec00f2febcc3c/package.json#L73)):*
> ```JSON
>     "react-router": "^4.1.1",
>     "react-router-dom": "^4.1.1",
>     "react-router-redux": "5.0.0-alpha.6",
> ```

alpha版に変える必要ってあるのでしょうか？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/6)*

**Comment by hrl7** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 73 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/6#-KnXKIqXjK8Q_W3xeOW9:-KnXLUN4CMJxucCKcXWr:b-jl21n1) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/9ab2d5df0349356f1bedbf27281ec00f2febcc3c/package.json#L73)):*
https://github.com/reactjs/react-router-redux
> This repo is for react-router-redux 4.x, which is only compatible with react-router 2.x and 3.x
The next version of react-router-redux will be 5.0.0 and will be compatible with react-router 4.x. It is currently being actively developed over there. Feel free to help out!

react-router v4でreact-router-reduxは5.0.0を使う必要があるけど, 5はまだalphaしかない

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/6)*

**Comment by fmsuvM** [comment]
Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/6)*

**Comment by fmsuvM** [comment]
Reviewed 1 of 11 files at r1, 8 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/6)*

**Pull request merged**
