### PR TITLE
update-buttonのレイアウト完了

### PR DESCRIPTION
**Pull request by tkatsuya**
アップデートボタンの位置を下部から画面上部にあるナビゲーションバーに組み込みました。

更新前と更新後で、更新マークに色が異なります。

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-app/23)

### CODE REVIEW

**Comment by fmsuvM** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23)*

**Comment by fmsuvM** [comment]
`ProjectManager.jsx` のUpdateButtonのimportは必要ない気がする

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23#-:-KoaXLtujMxOSbaZiC7p:biksvsi)*

**Comment by hrl7** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/components/ProjectManager.jsx, line 8 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23#-KoaYYHbj6VafWvxJXm9:-KoaYYHcDsfa1Hh7maM6:b-t3udxx) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/ce4ef4038507632a27750f9ade0d148a1d34aa62/src/components/ProjectManager.jsx#L8)):*
> ```JSX
> import SearchBar from './SearchBar';
> import Footer from './Footer';
> import UpdateButton from './UpdateButton';
> ```

tkdはこれを消せといっているのだな？
@fmsuvm expandして行についてコメントしておくといろいろ捗るよ。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23)*

**Comment by fmsuvM** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23#-:-KoaZFQSjQntj03Mk3Yo:bnfp4nl)*

**Comment by tkatsuya** [comment]
*[src/components/ProjectManager.jsx, line 8 at r1](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23#-KoaYYHbj6VafWvxJXm9:-Koa_UC1IaB7lrfr_SLZ:b4cgkec) ([raw file](https://github.com/fabnavi/fabnavi-app/blob/ce4ef4038507632a27750f9ade0d148a1d34aa62/src/components/ProjectManager.jsx#L8)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

tkdはこれを消せといっているのだな？
@fmsuvm expandして行についてコメントしておくといろいろ捗るよ。
</blockquote></details>

見落としていました。
言われて気づいたので削除しました。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-app/23)*

**Pull request merged**
